configure: Support --reconfigure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,6 @@
 #!/bin/bash
 
-echo $0 $* > configure.log
-
+PARAMETERS="$0 $*"
 CMAKEFLAGS=
 SRCDIR=$(dirname $(readlink -f $0))
 CURPATH="$PWD"
@@ -28,7 +27,7 @@ function help(){
 	echo "--build-wrappers         : build the wrappers for MPI, POSIX, etc. that is in the path"
 	echo "--use-ninja              : use the Ninja build tool instead of the old fashioned make"
 	echo "--verbose                : output the command but do not execute it"
-	echo
+	echo "--reconfigure            : run configure again with the parameters used the last time"
 	echo "The following list of options is only needed if you choose to build the wrappers with cmake"
 	echo "--with-mpicc=<file>    : path to the MPI C compiler"
 	echo "--with-mpicxx=<file>   : path to the MPI C++ compiler"
@@ -37,12 +36,22 @@ function help(){
 
 buildDIR="build"
 
-set -- `getopt -ul "help,version,with-boost:,with-libpq-type-dir:,with-libpqxx:,prefix:,with-cc:,with-cxx:,with-glib:,with-mpicc:,with-mpicxx:,with-libpq:,with-python:,with-likwid:,build-wrappers,use-ninja,verbose,build-dir:" hV "$@"`
+function reconfigure(){
+	if [[ ! -e "configure.log" ]] ; then 
+		echo "Error, didn't run configure before!" ; 
+		exit 1
+	fi 	
+	$(cat configure.log) 
+	exit $?
+}
+
+set -- `getopt -ul "help,version,reconfigure,with-boost:,with-libpq-type-dir:,with-libpqxx:,prefix:,with-cc:,with-cxx:,with-glib:,with-mpicc:,with-mpicxx:,with-libpq:,with-python:,with-likwid:,build-wrappers,use-ninja,verbose,build-dir:" hV "$@"`
 test $# -lt 1  && exit 1
 while test $# -gt 0 
 do
 	case "$1" in
 		--help) help; exit;;
+		--reconfigure) reconfigure;;
 		--version) cmake --version; exit;;
 		--prefix) prefix="$2"; shift;;
 		--with-boost) boostdir="$2"; shift;;
@@ -67,6 +76,8 @@ do
 	esac
 	shift
 done
+
+echo $PARAMETERS > configure.log
 
 TARGET_DIR="/usr/local"
 
